### ISSUE TITLE
Discord Bot for Phala Delegate/Mining (with Phala)

### ISSUE THREAD

**Issue by jamesbayly** [subquery/grants#12]
A notification bot that provides notification around Phala’s Delegate/Mining. It might monitor user’s worker/pool and alerts them by Discord when:

1. rewards available to claim（include owner reward and delegator reward） exceed defined value (default 100PHA)
2. notify about contribution / withdrawal request in owned pool.
3. notify about withrawal pending in queue in **owned** pool(reminder every 1d)
4. owned pool’s worker enter unresponsive state
5. notify about commission of pools you **delegated** change larger than 1%
6. notify about 25% drop of rewards

[Apply now](https://docs.google.com/forms/d/e/1FAIpQLSd9CZXANRMqXjyA-ckYsoYR4hf84295deDPlJEKQKXqYc4iyA/viewform)

**Comment by brittanyseales** [comment]
Completed by 100k (Lukasz Dobrowolski)
