### ISSUE TITLE
Analysis tool for Bifrost vToken (with Bifrost)

### ISSUE THREAD

**Issue by jamesbayly** [subquery/grants#14]
Bifrost SLP (Staking Liquidity Protocol) generates liquid-derivatives for multi-chains staking mechanism, vToken is a shadow asset minted through the SLP protocol, corresponding to the original chain staking Token, which can be traded, transferred or redeemed at any time. Users may need a SLP visual dashboard to decide their own product usage strategies.

The analysis tool might require multiple charts to display various aspects of vToken metrics such as vToken's TVL, 7d average staking APR, hourly TVL Change (7d/30d), total vToken Supply, vToken mint/redeem (7d), vToken holders (%), liquid ratio (7d), daily transfer volume, loan to value of vToken (timeseries) etc.

[Apply now](https://docs.google.com/forms/d/e/1FAIpQLSd9CZXANRMqXjyA-ckYsoYR4hf84295deDPlJEKQKXqYc4iyA/viewform)

**Comment by singulart** [comment]
Is this still available?
