### ISSUE TITLE
Bifrost Notification Bot (with Bifrost)

### ISSUE THREAD

**Issue by jamesbayly** [subquery/grants#17]
A notification bot that provides key notifications around minting & redemption events and monitors large minting/redemption events (or even frequent small minting events).

[Apply now](https://docs.google.com/forms/d/e/1FAIpQLSd9CZXANRMqXjyA-ckYsoYR4hf84295deDPlJEKQKXqYc4iyA/viewform)

**Comment by brittanyseales** [comment]
Completed by 'Isonar'
