### ISSUE TITLE
[$2,000] aUSD/kUSD Liquidation Tools (with Acala)

### ISSUE THREAD

**Issue by jamesbayly** [subquery/grants#20]
## Background

Acala's aUSD is an over collateralised stablecoin, meaning there is a liquidation event that occurs when the collaterialisation ratio falls below a threshold

The goal for liquidation is to sell off collateral assets from unsafe vaults and payback outstanding stablecoin debts. The collateral assets are sold on AcalaSwap first, then if unsuccessful, they will be sold on a Collateral Auction. There's usually great arbitrage opportunities to pick up collateral assets at a discount. 

## Challenge

Build UI for monitoring, understanding, and participating in liquidation events

## Judging Criteria

- How easy to use and intuitive the application is
- How easy you make it for participants to participate in these events
- Bonus if you can get notifications of events (e.g. via email or telegram bot) when they occur so you can participate

## Resources

- [Acala's offical docs about Liquidation auctions(https://docs.acaladollar.app/explore/liquidation-auction-opportunity)

[Apply Now](https://docs.google.com/forms/d/e/1FAIpQLSd9CZXANRMqXjyA-ckYsoYR4hf84295deDPlJEKQKXqYc4iyA/viewform?usp=sf_link)

**Comment by michael-d-anderson** [comment]
Our team will take on this Hack challenge. It should be a nice add on to the aUSD liquidation bot we are working on.

**Comment by eliotstock** [comment]
Hi @michael-d-anderson, did this get built at the hackathon? Do you have a repo?

**Comment by michael-d-anderson** [comment]
Hey @eliotstock We are almost done with the liquidation bot and then we'll try to tackle this notification system for liquidation events.
