### ISSUE TITLE
[$20,000] XCM UI Tool (with SubQuery, Moonbeam, Acala, and HydraDX)

### ISSUE THREAD

**Issue by jamesbayly** [subquery/grants#26]
# XCM UI tool

Sponsored equally between SubQuery, Moonbeam, Acala, and HydraDX for a total of a US20k prize.

## Background

XCM is a foundational new technology of Polkadot that allows heterogeneous blockchains to interoperate and seamlessly transfer value. XCM functionality recently debuted on Moonbeam, Acala, and HydraDX with the introduction of the XC-20 standard, a Substrate-native asset that conforms to ERC-20 standards allowing native communications and token transfers between the two chains without the need for bridges.

## Challenge

Currently, transferring assets via XCM between parachains can be a frustrating experience because the information displayed in block explorers is limited and disjointed. For example, you might see a transaction that initiated your XCM transfer but it is not clear:

1. that it is an XCM transaction, and
2. the destination of the transfer. 

## Submission Requirements

Your challenge is to build an explorer that tracks the status of a user's assets and reflects accurate locations for assets transferred via XCM. The main idea is to provide a nice UI and improve the UX for end users using XCM transfers. 

It may solve the following user stories:
- As a user that has just made a XCM transaction, when I enter my Ethereum/Substrate Tx hash, then I can see the outcome of that XCM transaction on the destination chain
- As a user with assets across multiple chains, when I enter my address, then I can see a list of all XCM i've done on each chain
- As an investor, when I view the aggregated data of all transactions across chains, then I can marvel in the technological breakthrough that XCM provides

## Judging Criteria

- How easy it is to understand and use for the average user. XCM is currently very powerful but it is complex, frustrating, and a terrible user experience. This is the most important aspect of this grant
- Functionality
- Your final submission **must** include at least Moonriver, Karura, and Basalisk, and must use SubQuery to index the XCM events

## Resources

- This [PR](https://github.com/paritytech/cumulus/pull/1228) will make this challenge a lot easier to complete (but it's still possible without)
- This [other bounty](https://github.com/galacticcouncil/amsterdot-bounties-2022/issues/2) will be useful and the examples there will help 
- [XCM Indexing Workshop (now slightly outdated thanks to the PR above)](https://www.crowdcast.io/e/xcm-multi-chain-explorer/register)
- [Polkadot XCM Documentation](https://wiki.polkadot.network/docs/learn-crosschain)
- [Moonbeam XCM Documentation](https://docs.moonbeam.network/builders/xcm/overview/)
- [SubQuery documentation](https://university.subquery.network/)

This is a technical challenge, and we will be providing more detailed support for applications that usual. Reach out, let us know, and we can work together on this

**Comment by ysun062** [comment]
Team NZ (Roy, Eric, Leo, Vincent) is going to attempt doing this project as part of the Polkadot Hackathon
