### ISSUE TITLE
[$6,000] RMRK Time-based NFT Explorer (with RMRK)

### ISSUE THREAD

**Issue by jamesbayly** [subquery/grants#27]
## Background

RMRK is a set of NFT legos that give NFTs infinite extensibility, hosted on the Kusama blockchain, Polkadot's canary network, without the need for parachains or smart contracts. 

## Challenge

Understanding and analysing the engagement with their NFTs is critical for creators. RMRK are looking for a time-based NFT explorer

This explorer would have some of the following features

- You can search for NFTs by name, collection, author, and or attribute
- For NFT collections, you can view details like current number of NFTs in the collection, number of sales over time, floor price, number of mints, number of unique owners etc
- For individual NFTs, you can view details like current state, owner, children, attached traits and resources etc
- Metrics and graphs that explore how many cross-collection NFTs exist over time

The key differentiator with this explorer is that it will be time based, meaning the user can scroll back into the history to see how the state of the selected NFT or NFT collection changes. E.g. they might be able to use a "time slider" (or similar UX) to load the state of a collection or NFT at a certain point in past time (e.g. see how many owners there were at that date).

## Judging Criteria

- Entries will only be accepted if use SubQuery to index RMRK NFTs
- You will be assessed on features first, and usability second
- Huge bonus points for how well you manage to build a user experience around "time slider" aspect of this challenge

## Resources

- [SubQuery's new Historical Query feature](https://doc.subquery.network/run_publish/historical.html)
- [RMRK Docs](https://docs.rmrk.app/)

**Comment by michael-d-anderson** [comment]
The Alphabit team will be working on this bounty as part of the Polkadot Hackathon for North America

**Comment by mmchougule** [comment]
Is this still open to apply to?
