### ISSUE TITLE
Substrate EVM NFT Indexer

### ISSUE THREAD

**Issue by jamesbayly** [subquery/grants#28]
Create a SubQuery project that indexes ERC721 NFTs from Moonbeam, Moonriver, Astar, and Shiden.

This must use SubQuery’s [multi chain indexing solution](https://academy.subquery.network/build/multi-chain.html)

## User stories
As a user, I would like to view the:
- name
- description
- collection
- price
- owner
of all NFTs from Moonbeam, Moonriver, Astar, and Shiden in a GraphQL request

## GraphQL Schema

The below is just a simple example of an excellent NFT API, your final solution does not need to match it exactly. You'll need to retrieve certain datapoints from the metadata attached to the NFT.

```graphql
type nft @entity {
  id: ID
  network: network
  contract_address: String
  amount: String
  collection: collection
  minted_block: Int
  minted_timestamp: Int # unix epoch timestamp
  minter_address: Address
  current_owner: Address
  contract_type: String # e.g. ERC721, RMRK
  name: String
  symbol: String
  token_uri: String
  image_uri: String
  description: String
  metadata: JSON
}

type collection @entity {
  id: ID
  network: network
  contract_address: String
  minted_block: Int
  minted_timestamp: Int # unix epoch timestamp
  minter_address: Address
  floor_price: Int
}

type nft_transfers @entity {
  id: ID
  network: network
  block: Int
  timestamp: Int
  transaction_id: String # Hash or extrinsic id
  nft: nft
  from: address
  to: address
}

type address @entity {
  id: ID
  network: network
}

type network @entity {
  id: ID
  name: String
}
```

**Comment by biomassives** [comment]
We have been preparing metadata indexer for a biodiversity credit NFT rewards system seeing how possible on substrate, and would like to audit Moonbeam, Moonriver, Astar, and Shiden  ..  diving in here would be cool.
