### ISSUE TITLE
[$100 in kSQT] Build starter project for Cheqd

### ISSUE THREAD

**Issue by siqi0408** [subquery/grants#44]
**Intro** 
We require a starter project for Cheqd with the following schema below. Check out https://github.com/subquery/cosmos-subql-starter for examples of other Cosmos based starter projects for ideas.
The challenge will be to source an RPC endpoint, (there maybe some free ones available) and also to find the protobuf files (a Google search will help).

**Project URL:** https://cheqd.io/

**Schema:**
type Transfers @entity {
  id: ID!
  blockHeight: BigInt
  txHash: String
  fromAddress: String
  toAddress: String
  amount: String
  denomination: String
}

**RPC:**
Need to source

**Protobuf:**
Need to source

**Comment by web3cdnservices** [comment]
https://github.com/subquery/cosmos-subql-starter/pull/43
