### ISSUE TITLE
[$50 in SQT] Build starter project for Cresent Network

### ISSUE THREAD

**Issue by siqi0408** [subquery/grants#46]
**Intro** 
We require a starter project for Cresent with the following schema below. Check out https://github.com/subquery/cosmos-subql-starter for examples of other Cosmos based starter projects for ideas.
The challenge will be to source an RPC endpoint, (there maybe some free ones available) and also to find the protobuf files (a Google search will help).

**Project URL**
 https://crescent.network/

**Schema:**
type Transfers @entity {
  id: ID!
  blockHeight: BigInt
  txHash: String
  fromAddress: String
  toAddress: String
  amount: String
  denomination: String
}

**RPC:**
https://github.com/cosmos/chain-registry

**Protobuf:**
Need to source

**Explorer**
https://mapofzones.com/zones/crescent-1/overview?columnKey=ibcVolume&period=24h

**important**
When you're done developing please make a PR to
https://github.com/subquery/cosmos-subql-starter/pulls

**Comment by web3cdnservices** [comment]
https://github.com/subquery/cosmos-subql-starter/pull/41

**Comment by jamesbayly** [comment]
Already supported internally
