### ISSUE TITLE
[$700 in kSQT] Integrate Space.ID

### ISSUE THREAD

**Issue by jamesbayly** [subquery/grants#54]
SPACE ID is building a universal name service network with a one-stop identity platform to discover, register, trade, manage web3 domains. It also includes a Web3 Name SDK & API for developers across blockchains and provides a multi-chain name service for everyone to easily build and create a web3 identity.

Follow the guide here to integrate the Web3 Name SDK from Space.ID in to the SubQuery Kepler app. https://docs.space.id/developer-guide/web3-name-sdk

When users link their accounts, we should first check ENS, then check SpaceID for a linked account name

You will want to update the [Network App](https://github.com/subquery/network-app) repo.

[SPACE ID Integration Overview.pdf](https://github.com/subquery/developer-guild/files/13358854/SPACE.ID.Integration.Overview.pdf)

**Comment by mogithehurt** [comment]
https://github.com/subquery/network-app/pull/604

**Comment by mogithehurt** [comment]
Merged https://github.com/subquery/network-app/pull/604

**Comment by jamesbayly** [comment]
This was merged and approved. Please reach out to @siqi0408  to help arrange your reward. Thanks!

**Comment by mogithehurt** [comment]
@jamesbayly  thank you, i did dm to @siqi0408 in discord.
